server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s;

    # React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia backend Ventas (IP privada de EC2 backend)
    location /api/v1/ventas {
        proxy_pass http://10.0.0.137:8080/api/v1/ventas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, Accept";
    }

    # Proxy hacia backend Despachos (IP privada de EC2 backend)
    location /api/v1/despachos {
        proxy_pass http://10.0.0.137:8081/api/v1/despachos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Content-Type, Accept";
    }
}
