server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Necesario para que Nginx resuelva nombres de contenedores dinámicamente
    resolver 127.0.0.11 valid=30s;

    # Redirigir todas las rutas al index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia backend Ventas
    location /api/ventas/ {
        set $upstream_ventas back-ventas;
        proxy_pass http://$upstream_ventas:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia backend Despachos
    location /api/despachos/ {
        set $upstream_despachos back-despachos;
        proxy_pass http://$upstream_despachos:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
